### PR TITLE
Release 5.0.0

### PR DESCRIPTION
**Pull request by atugushev**
_**Note** for those maintainers who would merge this after PR being approved, please use the "Squash and merge" button. Thanks!_

### CODE REVIEW

**Comment by atugushev** [comment]
@vphilippon would you like to mention a special note for windows users about `python -m pip install --upgrade pip-tools`?

**Comment by vphilippon** [comment]
@atugushev Yes, if you don't mind. That's a change worth noting. It may avoid some bad suprise for some people who read the Release Notes :) .

**Comment by atugushev** [comment]
@vphilippon could you drop a line here? I'll attach the text to the release notes.

**Comment by vphilippon** [comment]
@atugushev "Windows users, make sure to use `python -m pip install pip-tools` to avoid issues with `pip` self-update from now on."

**Comment by atugushev** [comment]
@vphilippon @auvipy thanks!

**Pull request merged**
