### PR TITLE
Hash packages without unpacking (Fixes #512 and #544)

### LINKED ISSUE #512: NotADirectoryError when running --generate-hashes
Running `pip-compile` works flawless, but pip-compile `--generate-hashes` produces the following error:

> Traceback (most recent call last):
>   File "/home/ric/.local/bin/pip-compile", line 11, in <module>
>     sys.exit(cli())
>   File "/home/ric/.local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/ric/.local/lib/python3.5/site-packages/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/home/ric/.local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/ric/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/home/ric/.local/lib/python3.5/site-packages/piptools/scripts/compile.py", line 186, in cli
>     hashes = resolver.resolve_hashes(results)
>   File "/home/ric/.local/lib/python3.5/site-packages/piptools/resolver.py", line 77, in resolve_hashes
>     return {ireq: self.repository.get_hashes(ireq) for ireq in ireqs}
>   File "/home/ric/.local/lib/python3.5/site-packages/piptools/resolver.py", line 77, in <dictcomp>
>     return {ireq: self.repository.get_hashes(ireq) for ireq in ireqs}
>   File "/home/ric/.local/lib/python3.5/site-packages/piptools/repositories/pypi.py", line 169, in get_hashes
>     for candidate in matching_candidates
>   File "/home/ric/.local/lib/python3.5/site-packages/piptools/repositories/pypi.py", line 169, in <setcomp>
>     for candidate in matching_candidates
>   File "/home/ric/.local/lib/python3.5/site-packages/piptools/repositories/pypi.py", line 176, in _get_file_hash
>     download_dir=tmpdir, only_download=True, session=self.session
>   File "/usr/lib/python3/dist-packages/pip/download.py", line 821, in unpack_url
>     hashes=hashes
>   File "/usr/lib/python3/dist-packages/pip/download.py", line 663, in unpack_http_url
>     unpack_file(from_path, location, content_type, link)
>   File "/usr/lib/python3/dist-packages/pip/utils/__init__.py", line 623, in unpack_file
>     untar_file(filename, location)
>   File "/usr/lib/python3/dist-packages/pip/utils/__init__.py", line 595, in untar_file
>     with open(path, 'wb') as destfp:
> NotADirectoryError: [Errno 20] Not a directory: '/tmp/tmprk7taktxbuild/LICENSE/LICENSE_STIX'
> 

##### Environment Versions

1. Ubuntu 16.04
1. Python 3.5.3
1. pip 9.0.1
1. pip-compile 1.9.0

This is my `requirements.in` file:

> 
> seaborn==0.7.1
> pandas==0.20.1
> numpy==1.12.1
> scipy==0.19.0
> tqdm==4.11.2
> matplotlib==2.0.2
>

### PR DESCRIPTION
**Pull request by suutari**
The PyPIRepository._get_file_hash used to call unpack_url, when
generating the hash.  It only needed the side effect of the downloaded
package being left in the download directory and the unpacking part was
actually unnecessary.  Change it to just open the (local or remote)
package as a file object and hash the contents without unpacking.

This makes it faster and lighter, since unpacking consumes CPU cycles
and disk space, and more importantly, avoids problems which happen when
some distribution has a file with the same name as a directory in
another.  Unpacking both to packages to the same directory will then
fail.  E.g. matplotlib-2.0.2.tar.gz has a directory named LICENSE, but
many other packages have a file named LICENSE.

Fixes #512, #544

##### Contributor checklist

- [X] Provided the tests for the changes (Thanks @mete0r)
- [X] Added the changes to CHANGELOG.md
- [x] Requested (or received) a review from another contributor

### CODE REVIEW

**Comment by suutari** [comment]
Can this be merged, please?

**Comment by graingert** [comment]
@suutari it would be even better if you pulled the SHA256 hashes from PyPI directly.

**Comment by graingert** [comment]
Fixes https://github.com/jazzband/pip-tools/issues/544

**Comment by graingert** [comment]
@suutari have a look at https://github.com/jazzband/pip-tools/issues/543 too.

**Comment by suutari-ai** [comment]
IMHO Pulling the hashesh from Warehouse is a different issue. This fixes two existing bugs. That would be a new feature, so I'd rather create a new PR of it.

**Comment by natemara** [comment]
This would also help solve sdispater/poet#21 - which is basically an extension of #512. It would be great to see this merged.

**Comment by vphilippon** [comment]
@suutari @suutari-ai Could you rebase on master, I'll be ready to get this in right away. Thanks!

**Comment by vphilippon** [comment]
Thanks for the PR!

**Pull request merged**
