### PR TITLE
A combo of CI unblocks via PRs #2106 #2134 #2141 #2142 #2146

### PR DESCRIPTION
**Pull request by webknjaz**
This is necessary to merge as a combo because of how the branch protection is configured.

##### Contributor checklist

- [x] Included tests for the changes.
- [ ] PR title is short, clear, and ready to be included in the user-facing changelog.

##### Maintainer checklist

- [x] Verified one of these labels is present: `backwards incompatible`, `feature`, `enhancement`, `deprecation`, `bug`, `dependency`, `docs` or `skip-changelog` as they determine changelog listing.
- [ ] Assign the PR to an existing or new milestone for the target version (following [Semantic Versioning](https://blog.versioneye.com/2014/01/16/semantic-versioning/)).

### CODE REVIEW

**Comment by webknjaz** [comment]
@hugovk @chrysle @Mr-Sunglasses @macro1 as soon as somebody approves this, everybody should get unblocked.

**Comment by webknjaz** [comment]
> Notably, I have no idea what fac71fcdf3cbf65ae696b807dae2ffeb19082097 does.
>

Basically, it turned out that the variable we relied on was always unavailable and so CI was always evaluating it the same way.
 51ec5edb8e7e6eae4ab52f35a861db90a9866505 seems to be an internal merge commit between your branches which duplicates al changes? I think that rebasing will making it disappear entirely, but I didn't check all of it for any discrepancies.

No, merge commits don't contain duplicates by their nature. We mustn't rebase, this is done on purpose so that the actual flow of history is preserved. If you rebase, you'll basically disregard the original commits replacing them with copies in a weird order and no link to reality.

**Comment by webknjaz** [comment]
The PyPy failure is rather weird. I saw similar problems on Windows but CPython. And I thought that was gone. I'll have to debug this last thing.

**Comment by webknjaz** [comment]
I was considering pinning to `pypy3.9-v7.3.14` like build did: [pypa/build@`a44675b` (#778)](https://github.com/pypa/build/pull/778/commits/a44675bcc15a7624fc55fa8f7e2687609a35a256#diff-1da8ce67b1810b20473f80b736705311db062337ce3753ba9cd5428c8fdc02ccR19).

But this implies that pypy-3.9 is EOL so I won't bother: https://github.com/pypy/pypy/issues/4958#issuecomment-2544481327.

**Comment by webknjaz** [comment]
> in hopes that the merge queues mechanism would just fast-forward `main` to it.

Nope, it still created another merge commit. Though, it's fine with me since it still is supposed to work, backtracking the PRs to mark as merged.

**Comment by WhyNotHugo** [comment]
Thanks for picking up this one and stabilising CI! :raised_hands:

**Pull request merged**
