### PR TITLE
Release 5.3.0

### PR DESCRIPTION
**Pull request by atugushev**

### CODE REVIEW

**Comment by atugushev** [comment]
@jazzband/pip-tools please, help with the review!

**Comment by atugushev** [comment]
@sfdye thank you!

**Comment by sfdye** [comment]
Just curious, how is this change log generated? By hand? By running a script? 

I see we are using Github Action, perhaps we could leverage this [action](https://github.com/release-drafter/release-drafter) to always generated change log as we merge PR.

**Comment by atugushev** [comment]
Currently, this log generation requires human interaction. Would be nice to use some GitHub action or `towncrier`. However, It's enjoyable worries to prepare releases for me, I don't mind :)

**Comment by atugushev** [comment]
@sfdye FYI https://github.com/jazzband/pip-tools/blob/master/CONTRIBUTING.md#project-release-process

**Pull request merged**
