### PR TITLE
[WIP] Add support for file based --extra-index-url to pip-sync

### PR DESCRIPTION
**Pull request by altendky**
Any `--extra-index-url` that are added inside the `requirements.txt` file are ignored. This change makes sure they are honoured.

This is a catchup for https://github.com/jazzband/pip-tools/pull/674

**Changelog-friendly one-liner**: Added support for --extra-index-urls options inside requirements.txt files

##### Contributor checklist

- [x] Provided the tests for the changes.
- [x] Gave a clear one-line description in the PR (that the maintainers can add to CHANGELOG.md on release).
- [ ] Assign the PR to an existing or new milestone for the target version (following [Semantic Versioning](https://blog.versioneye.com/2014/01/16/semantic-versioning/)).

### CODE REVIEW

**Comment by atugushev** [comment]
FTR, It's implemented in #824 as a comprehensive solution with support the other options, but a little bit stalled.

**Comment by atugushev** [comment]
Sorry, accidentally closed PR :(

**Comment by altendky** [comment]
Guess I should have been more careful about what PR to update.  :[  Probably ought to just close these if #824 does it all I guess.

**Comment by atugushev** [comment]
@altendky 

I've rebased #824, could you review/test it?

**Comment by atugushev** [comment]
Superseded by #824.

**Pull request closed without merging**
