### PR TITLE
Add a test for uncovered branch in the writer module

### PR DESCRIPTION
**Pull request by atugushev**
Now it's 100% coverage in the writer module.

### CODE REVIEW

**Comment by atugushev** [comment]
@AndydeCleyre awesome catch! 🎉 That's so tricky. I'll add a test for that case then.

**Comment by AndydeCleyre** [comment]
The test looks good :+1: . Is it still the plan to change the `has_hashes` tracking at all, or is this PR just for the test now?

**Comment by atugushev** [comment]
@AndydeCleyre 

Title updated.

**Comment by atugushev** [comment]
@AndydeCleyre 

Thank you for the analysis and for reviewing this!

**Pull request merged**
