### PR TITLE
Add -markerlib and pkg-resources to the list of PACKAGES_TO_IGNORE

### PR DESCRIPTION
**Pull request by cworth-gh**
On Debian unstable, mkvirtualenv 15.0.0 is installing two pseudo
packages (each with a version number of 0.0.0) as can be seen here:

```
$ mkvirtualenv foo
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/cworth/.virtualenvs/foo/bin/python2
Also creating executable in /home/cworth/.virtualenvs/foo/bin/python
Installing setuptools, pkg_resources, _markerlib, pip, wheel...done.
```

But then pip-sync will try to uninstall these packages (since nothing
explicitly depends on them) which will then cause pip stop working as
can be seen here:

```
$ pip-sync reqs.txt
Uninstalling pkg-resources-0.0.0:
  Successfully uninstalled pkg-resources-0.0.0

$ pip-sync reqs.txt
Traceback (most recent call last):
  File "/home/cworth/.virtualenvs/foo/bin/pip-sync", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
```

This commit adds these two package names to the PACKAGES_TO_IGNORE
list so that pip-sync will not try to uninstall them.

### CODE REVIEW

**Comment by tekacs** [comment]
Currently having to add these to every requirements.in file as extras - would be great to see this merged!

**Comment by palfrey** [comment]
I'd also like to see this in. Any thoughts on getting it merged? Is it worth setting up a separate PR with just the `sync.py` changes?

**Comment by amadornimbis** [comment]
I know this repository recently changed ownership, so I'm bumping this to see if anything needs to be changed in to get the first commit of this series merged?

**Comment by vphilippon** [comment]
@amadornimbis It definitely needs a rebase on master. The version update in setup.py and CHANGELOG.md should probably be remove too, as that'll be handled when doing the release (CHANGELOG entry itself should be kept though).

`pkg_resources` seems fine to add to the list, as it usually comes from setuptools anyway.
`_markerlib` is not a valid package name to install anyway (`pip install _markerlib` leads to and `InvalidRequirement` error), so I feel like it can be ignored too.

@davidovich Could you take a look at this? It seems like this would fix some error related to `pip-sync` uninstalling `pkg_resources`.

**Comment by oxplot** [comment]
As a workaround, you can setup the env with no setuptools and install it after activation:

```sh
virtualenv --no-setuptools venv
. venv/bin/activate
pip install setuptools
pip-sync requirements.txt
```

**Comment by vphilippon** [comment]
Will be completed in #613

**Comment by graingert** [comment]
instead of ignoring `-markerlib` what about also ignoring anything without a valid package name:

`^([A-Z0-9]|[A-Z0-9][A-Z0-9._-]*[A-Z0-9])$`

**Comment by graingert** [comment]
@vphilippon as defined: https://github.com/pypa/warehouse/blob/2b54d1e6a004ced695745d1f38a4304d81d6f8f7/warehouse/packaging/models.py#L82

**Comment by vphilippon** [comment]
@graingert Hm, maybe. but that should be opened in its own issue, that'll be lost on here.

**Comment by graingert** [comment]
@vphilippon https://github.com/jazzband/pip-tools/issues/618 done

**Pull request closed without merging**
