### PR TITLE
[WIP] GitHub actions

### PR DESCRIPTION
**Pull request by atugushev**

### CODE REVIEW

**Comment by atugushev** [comment]
@blueyed have you tried GitHub actions? :)

**Comment by blueyed** [comment]
Looks nice.  However at least with https://github.com/jazzband/pip-tools/pull/875/checks?check_run_id=195390732 there's an error:
```
  tox -e pipmaster
  shell: /bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.7.4/x64
GLOB sdist-make: /home/runner/work/pip-tools/pip-tools/setup.py
pipmaster create: /home/runner/work/pip-tools/pip-tools/.tox/pipmaster
pipmaster installdeps: -egit+https://github.com/pypa/pip.git@master#egg=pip, mock, pytest
pipmaster inst: /home/runner/work/pip-tools/pip-tools/.tox/.tmp/package/1/pip-tools-4.0.1.dev17+gc8ca9be.zip
pipmaster installed: atomicwrites==1.3.0,attrs==19.1.0,Click==7.0,importlib-metadata==0.19,mock==3.0.5,more-itertools==7.2.0,packaging==19.1,pip-tools==4.0.1.dev17+gc8ca9be,pluggy==0.12.0,py==1.8.0,pyparsing==2.4.2,pytest==5.1.0,six==1.12.0,wcwidth==0.1.7,zipp==0.5.2
pipmaster run-test-pre: PYTHONHASHSEED='617537163'
pipmaster run-test-pre: commands[0] | pip --version
pip 19.3.dev0 from /home/runner/work/pip-tools/pip-tools/.tox/pipmaster/src/pip/src/pip (python 3.7)
pipmaster run-test: commands[0] | pytest
ImportError while loading conftest '/home/runner/work/pip-tools/pip-tools/tests/conftest.py'.
tests/conftest.py:10: in <module>
    from piptools._compat import (
piptools/_compat/__init__.py:7: in <module>
    from .pip_compat import (
piptools/_compat/pip_compat.py:37: in <module>
    is_vcs_url = do_import("download", "is_vcs_url")
piptools/_compat/pip_compat.py:24: in do_import
    return getattr(imported, package)
E   AttributeError: module 'pip._internal.download' has no attribute 'is_vcs_url'
ERROR: InvocationError for command /home/runner/work/pip-tools/pip-tools/.tox/pipmaster/bin/pytest (exited with code 4)
___________________________________ summary ____________________________________
ERROR:   pipmaster: commands failed
```

**Comment by atugushev** [comment]
> Looks nice. However at least with https://github.com/jazzband/pip-tools/pull/875/checks?check_run_id=195390732 there's an error:

Do you mean it should be failed check?

**Comment by blueyed** [comment]
@atugushev 
Sure.

**Comment by atugushev** [comment]
> @atugushev
> It should not fail in the first place (since it was not failing before), but when it fails it should report the status correctly, of couse.

Yeah, right. That’s because of `continue-on-error`. Couldn’t  find a way to set correct (neutral?) check status.

**Comment by atugushev** [comment]
Close this for now. In general, it looks good to me, but, unfortunately, there is no way to set up `allow_failures` (continue-on-error works slightly different).

**Pull request closed without merging**
