### PR TITLE
Set up caching PyPI deps in GHA

### PR DESCRIPTION
**Pull request by webknjaz**
Ref https://github.com/jazzband/pip-tools/issues/1375#issuecomment-813212856

**Changelog-friendly one-liner**: Made GHA workflows faster by enabling pip cache

##### Contributor checklist

- [ ] Provided the tests for the changes.
- [x] Gave a clear one-line description in the PR (that the maintainers can add to CHANGELOG.md on release).
- [ ] Assign the PR to an existing or new milestone for the target version (following [Semantic Versioning](https://blog.versioneye.com/2014/01/16/semantic-versioning/)).

### CODE REVIEW

**Review by atugushev — APPROVED** [review]
LGTM 👍

**Comment by jezdez** [comment]
@webknjaz It would be great to follow patterns that we've established in other Jazzband repos, e.g. the pip cache dir should not be hardcoded here. Instead use `pip cache dir` to get it, [like in contextlib2](https://github.com/jazzband/contextlib2/blob/5f8498c19f12196ba087b207601665caecebb3e7/.github/workflows/test.yml#L21-L33). Thank you!

**Comment by webknjaz** [comment]
@jezdez got it, thanks for the feedback!

**Comment by jezdez** [comment]
> @jezdez got it, thanks for the feedback!
> 
> I think I copied this from one of my projects where `pip cache dir` is not a thing because it's old so I didn't bother overcomplicating it there. But I see the value of having it identified dynamically.

Gotcha, we switched to that CLI call only a bit ago when pip gained this subcommand, so no worries!

**Comment by webknjaz** [comment]
https://github.com/jazzband/pip-tools/pull/1389

**Comment by hugovk** [comment]
pip can now be cached via `actions/setup-python` to save a _lot_ of config:

https://github.com/actions/setup-python#caching-packages-dependencies

Please see https://github.com/jazzband/pip-tools/pull/1571 for an alternative.

**Pull request merged**
