### PR TITLE
Release 6.0.1

### PR DESCRIPTION
**Pull request by atugushev**

### CODE REVIEW

**Review by vphilippon — APPROVED** [review]
👍 🚀

**Comment by vphilippon** [comment]
Thanks @atugushev, I'll take care of completing the release, it's daytime over here :)

**Comment by atugushev** [comment]
Thank you, @vphilippon 🙏🏻Much appreciated!

**Review by bfox85 — COMMENTED** [review]
F

**Review by bfox85 — COMMENTED** [review]
Hg

**Pull request merged**
