### PR TITLE
Makes `compile` and `sync` directly runnable as modules

### PR DESCRIPTION
**Pull request by jamesbraza**
Before:

```bash
> python -m piptools.scripts.compile --help
```

After:

```bash
> python -m piptools.scripts.compile --help
Usage: python -m piptools.scripts.compile [OPTIONS] [SRC_FILES]...

  Compiles requirements.txt from requirements.in, pyproject.toml, setup.cfg,
  or setup.py specs.

Options:
  --version                       Show the version and exit.
...
```

##### Contributor checklist

- [ ] Included tests for the changes.
- [x] PR title is short, clear, and ready to be included in the user-facing changelog.

##### Maintainer checklist

- [x] Verified one of these labels is present: `backwards incompatible`, `feature`, `enhancement`, `deprecation`, `bug`, `dependency`, `docs` or `skip-changelog` as they determine changelog listing.
- [ ] Assign the PR to an existing or new milestone for the target version (following [Semantic Versioning](https://blog.versioneye.com/2014/01/16/semantic-versioning/)).

### CODE REVIEW

**Comment by chrysle** [comment]
Thanks! Could you add a functional test, please?

**Comment by jamesbraza** [comment]
@chrysle trying to do something [like this](https://stackoverflow.com/a/19011259), I am getting defeated by all the relative imports in `compile.py`.  So I opened https://github.com/jazzband/pip-tools/pull/2024, then I can come back to this the test of `__main__` behaviors

**Comment by webknjaz** [comment]
Is that instead of `python -m piptools compile`? Why?

**Comment by jamesbraza** [comment]
Oh yeah `python -m piptools compile` can work too actually, didn't know about that.  I am not attached to this PR if there's an alternate path to the same solution.  Feel free to close this out

**Comment by webknjaz** [comment]
> Oh yeah `python -m piptools compile` can work too actually, didn't know about that. I am not attached to this PR if there's an alternate path to the same solution. Feel free to close this out

Yep. I think I discovered it by reading the code. It should probably be documented better.

**Comment by webknjaz** [comment]
Oh, it's actually mentioned here https://pip-tools.rtfd.io/en/latest/#example-usage-for-pip-compile.

**Pull request closed without merging**
