### PR TITLE
Fix inconsistent handling of constraints comments with backtracking resolver

### LINKED ISSUE #1712: Inconsistent `via` comments for backtracking resolver on constrained requirements
`pip-compile` generates inconsistent `via` comments when using backtracking resolver on constrained requirements.

When a constrained `<constrained_requirements_file>.txt` file is not yet generated, `-c <requirements_file.txt>` references are correctly added to `via` comments, but they are removed when re-compiling the requirements when the constrained `<constrained_requirements_file>.txt` file already exists.

This seems to apply only to the backtracking resolver, since I wasn't able to reproduce the issue using the legacy resolver.

#### Environment Versions

1. OS Type: Linux (x86_64)
2. Python version: 3.10.8
3. pip version: 22.3
4. pip-tools version: 6.9.0 (also tried on `master` branch, at commit https://github.com/jazzband/pip-tools/commit/1fb2e69c4a58896eb5a860eb63f410ec7980913b)

#### Steps to replicate

I've created a reproduction repository (https://github.com/mkniewallner/pip-compile-inconsistent-via-backtracking-resolver) with a README and commits history that highlight the issue, but basically:

1. Create a `requirements.in` file with the following content:

```python
starlette==0.21.0
```
2. Create a `requirements-dev.in` file with the following content:

```python
-c requirements.txt

httpx==0.22.0
```
3. Run `pip-compile --resolver=backtracking requirements.in`
4. Run `pip-compile --resolver=backtracking requirements-dev.in`
5. Run `pip-compile --resolver=backtracking requirements-dev.in` again

#### Expected result

`pip-compile` writes the following `requirements-dev.txt` for both runs of `pip-compile --resolver=backtracking requirements-dev.in`:

```python
#
# This file is autogenerated by pip-compile with python 3.10
# To update, run:
#
#    pip-compile --resolver=backtracking requirements-dev.in
#
anyio==3.6.2
    # via
    #   -c requirements.txt
    #   httpcore
certifi==2022.9.24
    # via
    #   httpcore
    #   httpx
charset-normalizer==3.0.0
    # via httpx
h11==0.12.0
    # via httpcore
httpcore==0.14.7
    # via httpx
httpx==0.22.0
    # via -r requirements-dev.in
idna==3.4
    # via
    #   -c requirements.txt
    #   anyio
    #   rfc3986
rfc3986[idna2008]==1.5.0
    # via httpx
sniffio==1.3.0
    # via
    #   -c requirements.txt
    #   anyio
    #   httpcore
    #   httpx
```

#### Actual result

The first time `pip-compile --resolver=backtracking requirements-dev.in` is run (where `requirements-dev.txt` doesn't yet exist), the correct `requirements-dev.txt` is generated:

```python
#
# This file is autogenerated by pip-compile with python 3.10
# To update, run:
#
#    pip-compile --resolver=backtracking requirements-dev.in
#
anyio==3.6.2
    # via
    #   -c requirements.txt
    #   httpcore
certifi==2022.9.24
    # via
    #   httpcore
    #   httpx
charset-normalizer==3.0.0
    # via httpx
h11==0.12.0
    # via httpcore
httpcore==0.14.7
    # via httpx
httpx==0.22.0
    # via -r requirements-dev.in
idna==3.4
    # via
    #   -c requirements.txt
    #   anyio
    #   rfc3986
rfc3986[idna2008]==1.5.0
    # via httpx
sniffio==1.3.0
    # via
    #   -c requirements.txt
    #   anyio
    #   httpcore
    #   httpx
```

The second time `pip-compile --resolver=backtracking requirements-dev.in` is run (where `requirements-dev.txt` exists), the following diff is applied:

```diff
diff --git a/requirements-dev.txt b/requirements-dev.txt
index eaaa0f0..70ed934 100644
--- a/requirements-dev.txt
+++ b/requirements-dev.txt
@@ -5,9 +5,7 @@
 #    pip-compile --resolver=backtracking requirements-dev.in
 #
 anyio==3.6.2
-    # via
-    #   -c requirements.txt
-    #   httpcore
+    # via httpcore
 certifi==2022.9.24
     # via
     #   httpcore
@@ -22,14 +20,12 @@ httpx==0.22.0
     # via -r requirements-dev.in
 idna==3.4
     # via
-    #   -c requirements.txt
     #   anyio
     #   rfc3986
 rfc3986[idna2008]==1.5.0
     # via httpx
 sniffio==1.3.0
     # via
-    #   -c requirements.txt
     #   anyio
     #   httpcore
     #   httpx
```

### PR DESCRIPTION
**Pull request by mkniewallner**
Resolves #1712.

Investigating the root cause of the issue led to what could be a faulty condition in the backtracking resolver.

`self.existing_constraints` will always be empty when a generated `.txt` file doesn't exist yet, but will contain all the generated file dependencies when it does exist, so the condition that is removed by this PR will always evaluate to `False` for all dependencies in this case.
Consequently, [this condition](https://github.com/jazzband/pip-tools/blob/eff84765725fc15579d6626851910350d580ec8b/piptools/writer.py#L300) in the writer will also evaluate to `False`, preventing the retrieval of the constraints annotations when an already existing `.txt` file is updated.

There may be a specific reason this condition is here, but since the information only seems relevant for annotating the dependencies, it doesn't seem to me that it is relevant.

The PR also adds a specific test that ensures that running `pip-compile` twice (once with a non-existing `.txt` file, and once when it already exists) provides the same output for both resolvers. Without the change in the PR, the test fails for the backtracking resolver, but passes for the legacy one.

##### Contributor checklist

- [x] Provided the tests for the changes.
- [x] Assure PR title is short, clear, and good to be included in the user-oriented changelog

##### Maintainer checklist

- [x] Assure one of these labels is present: `backwards incompatible`, `feature`, `enhancement`, `deprecation`, `bug`, `dependency`, `docs` or `skip-changelog` as they determine changelog listing.
- [ ] Assign the PR to an existing or new milestone for the target version (following [Semantic Versioning](https://blog.versioneye.com/2014/01/16/semantic-versioning/)).

### CODE REVIEW

**Review by atugushev — APPROVED** [review]
Awesome! Thanks for the fix. Honestly, I don't remember the intention of [`ireq_key not in self.existing_constraints`](https://github.com/jazzband/pip-tools/blob/1fb2e69c4a58896eb5a860eb63f410ec7980913b/piptools/resolver.py#L773) condition. However, I'm glad the fix works for legacy and backtracking resolvers which is a good signal.

Minor comment below.

**Review by atugushev — APPROVED** [review]
Neat!

**Comment by mkniewallner** [comment]
Not sure why the CI is failing, but it doesn't seem to be related to this PR, as the same error appears on other workflows (https://github.com/jazzband/pip-tools/actions/runs/3382935861/jobs/5618360528#step:10:257).

**Comment by atugushev** [comment]
> Not sure why the CI is failing, but it doesn't seem to be related to this PR, as the same error appears on other workflows (https://github.com/jazzband/pip-tools/actions/runs/3382935861/jobs/5618360528#step:10:257).

Yeah, that's unrelated to the PR. I'm gonna merge this anyway.

**Pull request merged**
