### PR TITLE
Drop support for Python 3.7

### PR DESCRIPTION
**Pull request by chrysle**
Drop support for Python 3.7 which is EOL in the end of June.

##### Contributor checklist

- [ ] Provided the tests for the changes.
- [x] Assure PR title is short, clear, and good to be included in the user-oriented changelog

##### Maintainer checklist

- [x] Assure one of these labels is present: `backwards incompatible`, `feature`, `enhancement`, `deprecation`, `bug`, `dependency`, `docs` or `skip-changelog` as they determine changelog listing.
- [ ] Assign the PR to an existing or new milestone for the target version (following [Semantic Versioning](https://blog.versioneye.com/2014/01/16/semantic-versioning/)).

### CODE REVIEW

**Review by atugushev — COMMENTED** [review]
Bump version here also, please:

https://github.com/jazzband/pip-tools/blob/b05acb1428252af6d596da33308579bb0698a0e3/.pre-commit-config.yaml#L11-L15

**Comment by chrysle** [comment]
Sounds like a good suggestion.

**Comment by chrysle** [comment]
Yesterday was the last day of support.

**Comment by webknjaz** [comment]
I wonder if a release could be made right before this is merged..

**Comment by atugushev** [comment]
The release 6.14.0 is blocked by  https://github.com/jazzband/pip-tools/pull/1863#issuecomment-1611627683. Release drafter now suggests `7.0.0` release.

**Comment by webknjaz** [comment]
@chrysle plz add `git revert cfef6aa` to this.

**Review by atugushev — APPROVED** [review]
Ready to go 👍🏻

**Pull request merged**
