### PR TITLE
Release 6.3.0

### PR DESCRIPTION
**Pull request by atugushev**
##### Contributor checklist

- [ ] Provided the tests for the changes.
- [ ] Assure PR title is short, clear, and good to be included in the user-oriented changelog

##### Maintainer checklist

- [x] Assure one of these labels is present: `backwards incompatible`, `feature`, `enhancement`, `deprecation`, `bug`, `dependency`, `docs` or `skip-changelog` as they determine changelog listing.
- [x] Assign the PR to an existing or new milestone for the target version (following [Semantic Versioning](https://blog.versioneye.com/2014/01/16/semantic-versioning/)).

### CODE REVIEW

**Comment by AndydeCleyre** [comment]
Just checking: no changes to supported Python or pip versions for this release?

**Comment by atugushev** [comment]
Thanks for the heads-up. We should update also [version compatibility](https://github.com/jazzband/pip-tools#versions-and-compatibility) table.

**Comment by atugushev** [comment]
@AndydeCleyre 
> no changes to supported Python or pip versions for this release?

I think we can keep current pins as long as they work.

**Comment by AndydeCleyre** [comment]
> ... we should test on CI pip-tools against all minor pip>=20.3 versions or update `pipprevious` tox-env and drop anything less than that.

I trust your version management calls; is that slated for inclusion in this PR?

**Comment by atugushev** [comment]
@AndydeCleyre 

> is that slated for inclusion in this PR?

No, actually. Python 3.10 is going to be released in early October, so we can update pip-tools' deps by then.

**Review by AndydeCleyre — APPROVED** [review]
Looks good, thanks!

**Comment by atugushev** [comment]
Thanks, @AndydeCleyre 🙏🏻

**Pull request merged**
