### PR TITLE
Fixing OutputWriter._iter_lines for pip 8.1.1 or below

### PR DESCRIPTION
**Pull request by Lucas-C**
##### Contributor checklist

- [x] Provided the tests for the changes:
An existing test ensures this does not introduces any regression: https://github.com/jazzband/pip-tools/blob/master/tests/test_writer.py
- [x] Added the changes to CHANGELOG.md
I don't think this is needed as it is a fix.
- [ ] Requested (or received) a review from another contributor
Nope. Anyone please ? :)

### CODE REVIEW

**Comment by Lucas-C** [comment]
I'm totally willing to add a test, but I don't understand what you want to test here ?

My change is in `OutputWriter._iter_lines` while you asked me to add a test for `OutputWriter._format_requirement` which is not affected by my changes (`marker=None` is going to be passed as an argument).

Also this aims to fix a compatibility issue with pip 8.1.1 or below, so maybe the best way to test it would be to add a `pip==8.1.1` testenv in https://github.com/jazzband/pip-tools/blob/master/tox.ini#L7 ?

**Comment by vphilippon** [comment]
You're right, I was under the impression that the formatting was changed, but it's actually the value passed that might be different. That would be a different test.

Adding a test suite in tox using `pip 8.1.1` seems reasonable to me, as this version (while having a more recent bugfix version) seems to still be common in the wild.
You can go ahead and add a test environment with `pip 8.1.1`.

Also, sorry for the delay, life happened. Thank you for your time!

**Comment by Lucas-C** [comment]
I added a test tox env,
but I'm not 100% sure I got it right :)

**Comment by vphilippon** [comment]
@Lucas-C You also have to add the new `pip 8.1.1` tox environment in `.appveyor.yml`, for each python version already listed. That's for the Windows tests.
We're almost there, pretty sure we'll be done after that.
Thanks again.

**Comment by Lucas-C** [comment]
No problem: done !

**Comment by vphilippon** [comment]
Thanks for your contribution!

**Comment by Lucas-C** [comment]
Thanks for your help :)

**Pull request merged**
