### PR TITLE
Remove newlines from description in setup.py

### LINKED ISSUE #594: README broken on PyPI (must be reStructuredText)
The [package description](https://pypi.python.org/pypi/pip-tools/) on PyPI is unreadable since PyPI expects the README in [reStructuredText](http://www.sphinx-doc.org/en/stable/rest.html) file format and we use MarkDown.

Solution A: Convert to reST
---------------------

1. Rename the current `README.md` to `README.rst`
1. Replace the markdown of the badges and the code samples ([example](https://github.com/Organice/djangocms-maps/blob/master/README.rst))
1. Add a `long_description=read_file('README.rst')` line to `setup.py` ([example](https://github.com/Organice/djangocms-maps/blob/master/setup.py#L50))

Solution B: Process before Upload
-------------------

1. Integrate [pypandoc](https://pypi.python.org/pypi/pypandoc) in `setup.py` ([example](https://github.com/jrief/djangocms-cascade/blob/master/setup.py#L7-L14))
1. Add a `long_description=convert('README.md', 'rst')` line to `setup.py` ([example](https://github.com/jrief/djangocms-cascade/blob/master/setup.py#L49))

------------

Both solutions above will render a nicely formatted, HTML-styled package description on PyPI.

Quality Assurance
--------------

Optionally, you may check your README with [checkdocs](https://github.com/Organice/djangocms-maps/blob/master/tox.ini#L13-L19) before uploading the package to PyPI, because sometimes the reST-to-HTML conversion that PyPI uses fails -- and renders a still hard-to-read, broken, unformatted package description.

### PR DESCRIPTION
**Pull request by vphilippon**
Fixes #594
Applying the fix given here: https://github.com/pypa/warehouse/issues/2600#issuecomment-346156317

And the result, using the pypi test instance: https://testpypi.python.org/pypi/pip-tools/1.10.2rc3

### CODE REVIEW

**Comment by davidovich** [comment]
Wow! at last!
LGTM

**Comment by jezdez** [comment]
@vphilippon Wow, what a rabbit hole filled with yaks. Good work! 👏

**Comment by vphilippon** [comment]
Credits to @bittner for tackling this in the first place 🥇

**Comment by bittner** [comment]
Lucky me! I usually do a `package.__doc__.strip()` as a reflex. I never stepped into that issue. Good to know. And thanks for investigating. :+1:

**Pull request merged**
