### PR TITLE
Unshallow git clone on RTD build

### LINKED ISSUE #1939: Old 0.1 version on the latest docs
RTD built [latest](https://pip-tools.readthedocs.io/en/latest/) doc on b55abdc31e5a905389da26352a9beab2a6c87bfa commit using `0.1.dev128` version.

#### Expected result

There should be `v7.1.1.devN`

#### Actual result

Screenshot:
image

#### Additional context

Logs on [RTD](https://readthedocs.org/projects/pip-tools/builds/21423718/):
```
$ python -m sphinx -T -E -W --keep-going -b dirhtml ...
Running Sphinx v6.2.1
pip-tools version: 0.1.dev128
pip-tools release: 0.1.dev128
...
```

### PR DESCRIPTION
**Pull request by atugushev**
Fetch full history so that setuptools-scm could detect correct version.

For the context:
- https://github.com/pypa/setuptools_scm/issues/790
- https://docs.readthedocs.io/en/latest/build-customization.html#unshallow-git-clone

Fixes #1939.

##### Contributor checklist

- [ ] Provided the tests for the changes.
- [ ] Assure PR title is short, clear, and good to be included in the user-oriented changelog

##### Maintainer checklist

- [ ] Assure one of these labels is present: `backwards incompatible`, `feature`, `enhancement`, `deprecation`, `bug`, `dependency`, `docs` or `skip-changelog` as they determine changelog listing.
- [ ] Assign the PR to an existing or new milestone for the target version (following [Semantic Versioning](https://blog.versioneye.com/2014/01/16/semantic-versioning/)).

### CODE REVIEW

**Review by chrysle — APPROVED** [review]

**Comment by webknjaz** [comment]
This is missing fetching the tags. I think there's something in `tox.ini` for that and it'd be wise to put this into a Sphinx extension to reduce duplication...

**Comment by atugushev** [comment]
Apparently, It [fetches](https://readthedocs.org/projects/pip-tools/builds/21446450/) tags from the last 50 commits:
```
git fetch origin --force --prune --prune-tags --depth 50 ...
```

There's a possibility that 50 commits may not be enough, so explicitly fetching all tags might be a good idea.

**Comment by webknjaz** [comment]
Exactly. This is a known issue that I've been facing since the times when Travis CI was still popular, which is why I fetch all of these.

**Comment by chrysle** [comment]
> and it'd be wise to put this into a Sphinx extension to reduce duplication...

Could you tell me more? How and where would that custom extension come to use?

**Comment by webknjaz** [comment]
It can be just a `setup()` function in `conf.py`. Though I realized that someone removed direct use of setuptools-scm, meaning that it must happen before Sphinx runs. So my idea would work only if we were to determine the version independently from packaging.

**Pull request merged**
