### PR TITLE
Modify Copy for Zip Import

### PR DESCRIPTION
**Pull request by munagekar**
Change Copy Behaviour for ZipImport

**Changelog-friendly one-liner**: Change Copy Behaviour for ZipImport

## Related
https://github.com/pypa/pipenv/issues/4125

##### Contributor checklist

- [ ] Provided the tests for the changes.
- [x] Gave a clear one-line description in the PR (that the maintainers can add to CHANGELOG.md on release).
- [ ] Assign the PR to an existing or new milestone for the target version (following [Semantic Versioning](https://blog.versioneye.com/2014/01/16/semantic-versioning/)).

### CODE REVIEW

**Comment by atugushev** [comment]
Hello @munagekar,

What is the issue are you trying to resolve? Any details?

**Comment by munagekar** [comment]
I am facing the trouble while installing [ecdsa](https://github.com/warner/python-ecdsa) as a transitive dependency with pipenv(pypa/pipenv#4125) which depends on pip-tools.

I get the following error.
```
TypeError: can't pickle zipimport.zipimporter objects
``` 
I was able to fix it by adding the changes.

**Comment by munagekar** [comment]
@atugushev 
I was facing trouble while installing [ecdsa](https://github.com/warner/python-ecdsa) as a transitive dependency with pipenv(pypa/pipenv#4125) which depends on pip-tools.

I get the following error.
```
TypeError: can't pickle zipimport.zipimporter objects
``` 
I was able to fix it by adding the changes.

**Comment by atugushev** [comment]
@munagekar 

Could you raise an issue with reproducible steps (best via docker)? I can't reproduce it locally on MacOS X.

**Comment by munagekar** [comment]
I am unable to reproduce this issue. It worked successfully with linux.

**Comment by atugushev** [comment]
@munagekar feel free to reach us out if the bug pops-out again. Thanks for the PR!

**Pull request closed without merging**
