### PR TITLE
Convert index.rst to Markdown

### PR DESCRIPTION
**Pull request by chrysle**
Related to #1871 

##### Contributor checklist

- [ ] Provided the tests for the changes.
- [x] Assure PR title is short, clear, and good to be included in the user-oriented changelog

##### Maintainer checklist

- [ ] Assure one of these labels is present: `backwards incompatible`, `feature`, `enhancement`, `deprecation`, `bug`, `dependency`, `docs` or `skip-changelog` as they determine changelog listing.
- [ ] Assign the PR to an existing or new milestone for the target version (following [Semantic Versioning](https://blog.versioneye.com/2014/01/16/semantic-versioning/)).

### CODE REVIEW

**Comment by webknjaz** [comment]
@chrysle it looks like MyST treats the included document as MD: https://pip-tools--1874.org.readthedocs.build/en/1874/. Maybe it needs some param?

**Comment by webknjaz** [comment]
Are you sure eval is what's needed? Doesn't the native include work?

**Comment by chrysle** [comment]
I skimmed through the MyST docs and found [this](https://myst-parser.readthedocs.io/en/v0.15.1/sphinx/use.html#include-rst-files-into-a-markdown-file).

**Comment by webknjaz** [comment]
Interesting.. Does combining two PRs work better?

**Comment by chrysle** [comment]
You mean the Markdown README **and** converted index? It was like that before you asked me to move the _index_ into a separate PR. It worked, but I had to ignore that MyST warning.

**Comment by webknjaz** [comment]
Yeah. If it's the only way to make it work, we'd have to go for it. And maybe figure out the warning later.

**Comment by chrysle** [comment]
This might be related to the docs failure: executablebooks/MyST-Parser#521

**Comment by webknjaz** [comment]
Interesting.. Does combining two PRs work better? Where do we use autodoc?

**Comment by chrysle** [comment]
We don't, but that generally has to do with link rendering in the `eval-rst` directive. I have done some testing and conclude that the handling of explicit links is broken when they are parsed through sphinx's `include`, or  when links are provided directly, like in executablebooks/MyST-Parser#391  

I'm therefore in favor of including the README from the Markdown index. Or should I submit an issue and wait for the answer?

**Comment by webknjaz** [comment]
No, go ahead and make a combined PR. But you can also document this on their tracker..

**Comment by webknjaz** [comment]
Looks like this can be closed now.

**Pull request closed without merging**
