### PR TITLE
Remove appveyor in favor of GitHub Actions

### LINKED ISSUE #1230: Remove AppVeyor use?
#1229 has removed the use of Travis-CI in favor of the GitHub Actions setup, which also supports Windows.

I've already removed the pull request merge requirement for AppVeyor following the discussion there.

Should we remove AppVeyor completely?

Refs: https://github.com/jazzband-roadies/help/issues/74

### PR DESCRIPTION
**Pull request by jdufresne**
Resolves #1230.

Remove appveyor in favor of GitHub Actions

**Changelog-friendly one-liner**: 

##### Contributor checklist

- [x] Provided the tests for the changes.
- [x] Gave a clear one-line description in the PR (that the maintainers can add to CHANGELOG.md on release).
- [x] Assign the PR to an existing or new milestone for the target version (following [Semantic Versioning](https://blog.versioneye.com/2014/01/16/semantic-versioning/)).

---

The appveyor matrix covers exactly the same targets as the Windows
target in the GitHub Actions configuration (ci.yml) except it is much
slower. Improve CI response time and therefore reduce contributor
friction.

### CODE REVIEW

**Comment by jdufresne** [comment]
appveyor must also be disabled through its web UI. I can go ahead with that is this is approved/landed.

**Comment by jezdez** [comment]
@jdufresne FWIW I think I'll need to delete the Appveyor project since you shouldn't have the permissions to do so.

**Review by atugushev — APPROVED** [review]
LGTM 👍

**Comment by jdufresne** [comment]
@jezdez Do you mind going ahead with disabling appveyor?

**Comment by jezdez** [comment]
@jdufresne Done!

**Pull request merged**
