### PR TITLE
Release 6.6.0

### PR DESCRIPTION
**Pull request by atugushev**

### CODE REVIEW

**Review by hramezani — APPROVED** [review]

**Comment by atugushev** [comment]
Thanks @hramezani 🙏🏻

**Comment by ssbarnea** [comment]
So time to use https://github.com/jazzband/pip-tools/releases page to convert the draft into a release?

Before doing this, can you please enable the discussions on the project? I do not have enough right to do it myself. If you do, you will see a checkbox to create a discussion thread on publish.

**Comment by atugushev** [comment]
I've missed your message and already published the release, sorry.

**Comment by atugushev** [comment]
> Before doing this, can you please enable the discussions on the project?

I've missed your message and already published the release, sorry. There is an open discussion about the "discussing page", see: https://github.com/orgs/jazzband/teams/pip-tools/discussions/13

**Comment by atugushev** [comment]
However, I don't have such permission to enable discussions. We should confirm this with @jezdez first on the thread above.

**Comment by ssbarnea** [comment]
Maybe that is the cherry that would finally push https://github.com/jazzband/pip-tools/issues/1434 to make it happen. At least projects un pypa org are not prevented from enabling discussions... not to mention that this org would be better suited for our project.

**Pull request merged**
