### PR TITLE
Add `--only-extra` option to `pip-compile`

### LINKED ISSUE #1959: Add support for `--only-extra`
Currently, pip-tools can't compile only extra dependencies. Wouls be nice to have a new option `--only-extra`, for example:

```bash
# includes test deps only
pip-compile --only-extra=test -c requirements.txt -o test-requirements.txt
```

Note `-c requirements.txt` so that common sub-dependencies are in sync with `requirements.txt`.

_Originally posted by @atugushev in https://github.com/jazzband/pip-tools/issues/1957#issuecomment-1669985803_

### PR DESCRIPTION
**Pull request by atugushev**
Resolves #1959.
Refs #1957.

##### Contributor checklist

- [x] Included tests for the changes.
- [x] PR title is short, clear, and ready to be included in the user-facing changelog.

##### Maintainer checklist

- [x] Verified one of these labels is present: `backwards incompatible`, `feature`, `enhancement`, `deprecation`, `bug`, `dependency`, `docs` or `skip-changelog` as they determine changelog listing.
- [ ] Assign the PR to an existing or new milestone for the target version (following [Semantic Versioning](https://blog.versioneye.com/2014/01/16/semantic-versioning/)).

### CODE REVIEW

**Comment by webknjaz** [comment]
I'm not sure if it is reasonable to support this. It's out of standard and encourages people to misuse [`Provides-Extra`](https://packaging.python.org/en/latest/specifications/core-metadata/#provides-extra-multiple-use) by exposing them to their end-users.

Extras are a public API for installing additional runtime dependencies together with the mandatory ones. All the installers, like pip, always include normal deps. Advertising this to people would cause confusion, especially, when used with `pip install thing[extra] -c constraints.txt` and `--generate-hashes`.

This PR should at least have a huge disclaimer explaining https://github.com/jazzband/pip-tools/pull/1681#issuecomment-1666966545 bundled in the docs and maybe the help string. And maybe don't call it `--only-extra` — having something more explicit like `--only-extract-extra` to signify that it's extracted as a standalone dependency source.

**Comment by webknjaz** [comment]
Oh, and maybe hold this until #1681 is merged? I don't want to keep introducing conflicts for the contributor all the time…

**Comment by atugushev** [comment]
I don't want to encourage bad practices, so I'll close this. If someone finds this feature sensible, please feel free to reopen the issue. Thanks for the feedback!

**Comment by webknjaz** [comment]
The dependency groups PEP is going to be the correct solution so it should be implemented instead. I think it'd okay to do this even before it's fully accepted.

**Pull request closed without merging**
