### PR TITLE
Fix leaked URLs with credentials in the output

### LINKED ISSUE #1137: Clear-text password leaked via index URL
Clear-text username and password from index URL are directly put to the generated `requirements.txt` files, not hidden in any way as `pip` does, and ignoring the `--no-index-url`/`--no-trusted-host` options.

#### Environment Versions

1. OS Type: Linux
1. Python version: 3.6
1. pip version:  20.1
1. pip-tools version: 5.1.1

#### Steps to replicate

1. Set env var `PIP_INDEX_URL` to `https://username:password@hostname/...`
2. Set env var `PIP_TRUSTED_HOST` to `hostname`
2. Run `pip-compile --no-index --no-emit-trusted-host`

#### Expected result

No index URL is added due to `--no-index`.

OR: No credentials included.

OR: Credentials are hidden.

#### Actual result

Index URL with credentials is added to the requirements.txt file:

```
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --index-url=https://username:password@hostname/... --no-emit-trusted-host --no-index --output-file=requirements.txt --trusted-host=hostname requirements.in
#
………
```

...

### PR DESCRIPTION
**Pull request by atugushev**
Fixes #1137.
Reds #811 and #1028.

**Changelog-friendly one-liner**: Fix leaked URLs with credentials in `pip-compile`'s output.

##### Contributor checklist

- [X] Provided the tests for the changes.
- [X] Gave a clear one-line description in the PR (that the maintainers can add to CHANGELOG.md on release).
- [x] Assign the PR to an existing or new milestone for the target version (following [Semantic Versioning](https://blog.versioneye.com/2014/01/16/semantic-versioning/)).

### CODE REVIEW

**Comment by atugushev** [comment]
@AndydeCleyre 

> If you think it's appropriate, I would suggest renaming `default_index_url` in `compile.py` to better reflect that it's not the _real_ default URL (redacted and used only for the help string).

Yeah, naming is hard :) For example:
- `display_index_url`
- `help_index_url`
- `redacted_default_index_url`
- `show_default_index_url`
- `pipconf_index_url`

What's your suggestion?

I'm also tempted to move some logic to a function to not waste global scope:

```python
def _get_pip_default(option_name):
    install_command = create_command("install")
    pip_defaults = install_command.parser.get_default_values()
    return getattr(pip_defaults, option_name)

...

@click.option(
    "-i",
    "--index-url",
    help="Change index URL (defaults to {})".format(
        redact_auth_from_url(
            _get_pip_default("index_url")
        )
    ),
    envvar="PIP_INDEX_URL",
)

```


What do you think?

**Comment by AndydeCleyre** [comment]
Moving that into the function looks good. Otherwise, I'd say `redacted_default_index_url` is the most straightforward choice.

**Comment by atugushev** [comment]
@AndydeCleyre 

Addressed in 302d46b.

**Comment by atugushev** [comment]
Thanks @AndydeCleyre for reviewing this!

**Pull request merged**
