### PR TITLE
Release 4.2.0

### PR DESCRIPTION
**Pull request by atugushev**
The pip's release is on the way. Let's release pip-tools then!

See https://github.com/pypa/pip/issues/6993

### CODE REVIEW

**Comment by atugushev** [comment]
Since #911, the next releases should be done via PR (which is excellent!).

```
$ git push upstream master
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 8 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 679 bytes | 679.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.

> remote: error: At least 1 approving review is required by reviewers with write access.

To github.com:jazzband/pip-tools.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:jazzband/pip-tools.git'
```

TODO: update "Project Release Process" in CONTRIBUTING.md.

**Comment by atugushev** [comment]
@davidovich thanks! I'll cancel CIs and merge this then.

**Comment by codingjoe** [comment]
🎉

**Comment by atugushev** [comment]
I've uploaded the release on the jazzband PyPI server, waiting for approvement by @davidovich or @vphilippon.

**Comment by atugushev** [comment]
`pip-tools v4.2.0` is released! Thanks to all contributors, especially: @georgek, @jamescooke, @AndydeCleyre, and @hramezani!

Many thanks to @codingjoe and @blueyed for helping to review PRs.

Cheers 🎉

**Pull request merged**
