### PR TITLE
Add support for --find-links in pip-compile output

### PR DESCRIPTION
**Pull request by atugushev**
This adds support to pip-compile for the -f, --find-links <url> flag in the input requirements.in. Rebased #704 and adjusted tests. **Thanks @estan for the contribution!**

**Changelog-friendly one-liner**: Add support for `--find-links` in `pip-compile` output.

##### Contributor checklist

- [X] Provided the tests for the changes.
- [X] Requested a review from another contributor.
- [X] Gave a clear one-line description in the PR (that the maintainers can add to CHANGELOG.md on release).
- [x] Assign the PR to an existing or new milestone for the target version (following [Semantic Versioning](https://blog.versioneye.com/2014/01/16/semantic-versioning/)).

### CODE REVIEW

**Comment by suutari** [comment]
FYI, I've implemented something similar in #453 over a year ago. Though with the difference that only relative directories are written out, since absolute ones rarely make sense to be stored into the txt file. If this gets merged, then #453 can be closed (or the other way around).

**Comment by atugushev** [comment]
Hello @suutari,

Thank you for pointing that out! I agree there should be relative links. I'll port your code here if you don't mind.

**Comment by atugushev** [comment]
@suutari 

> Though with the difference that only relative directories are written out

I've found an interesting [FIXME](https://github.com/pypa/pip/blob/master/src/pip/_internal/req/req_file.py#L241-L244):
```
# FIXME: it would be nice to keep track of the source
# of the find_links: support a find-links local path
# relative to a requirements file.
```

Maybe we should fix it on the `pip` side instead of hard coding that case in the `pip-tools`?

**Comment by estan** [comment]
@atugushev I've been completely swamped and almost forgot about my PR. Thanks for taking care of this!

**Pull request merged**
