### PR TITLE
Add support for pip==23.1 where removed FormatControl in WheelCache

### PR DESCRIPTION
**Pull request by atugushev**
https://github.com/pypa/pip/pull/11872

##### Contributor checklist

- [ ] Provided the tests for the changes.
- [x] Assure PR title is short, clear, and good to be included in the user-oriented changelog

##### Maintainer checklist

- [x] Assure one of these labels is present: `backwards incompatible`, `feature`, `enhancement`, `deprecation`, `bug`, `dependency`, `docs` or `skip-changelog` as they determine changelog listing.
- [x] Assign the PR to an existing or new milestone for the target version (following [Semantic Versioning](https://blog.versioneye.com/2014/01/16/semantic-versioning/)).

### CODE REVIEW

**Comment by jeteve** [comment]
Any idea when this is going to release in Pypi? It's very broken with the newest pip.

**Comment by atugushev** [comment]
It's released as part of `pip-tools v6.13.0`.

**Comment by BrendanJM** [comment]
I also saw my builds randomly break related to this (`pip-tools` was pinned to `6.12.3`, but the pulling the latest pip `23.1` seems to have broken things). I'm going to post the relevant part of the stack tract here to hopefully aid in searchability for other users encountering the issue (at the time of this post, googling this error doesn't yield relevant results):

```
... 
... File ".../python3.9/site-packages/piptools/repositories/pypi.py", line 237, in get_dependencies
         wheel_cache = WheelCache(self._cache_dir, self.options.format_control)
         TypeError: __init__() takes 2 positional arguments but 3 were given
```

I can confirm that updating to `pip-tools v6.13.0` resolved the issue for me.

**Comment by AndydeCleyre** [comment]
@BrendanJM pip-tools doesn't usually cap the required pip version before releasing a new version compatible with newer pip releases, which sometimes creates these windows.

For my own CI reliability needs, I made and maintain a metadata-only package https://github.com/andydecleyre/pip-and-pip-tools

**Comment by BrendanJM** [comment]
That’s a clever workaround. It would be nice to see some strategy for mitigating these breakages from the core pip-tools team. 

This is not the first (or second) time pip-tools has broken with a new pip release. I love the tool, but it’s hard go build buy in for a tool that has a history of suddenly breaking like this, and these bugs are usually not simple or intuitive to establish a root cause, since none of our dependencies changes, yet they suddenly break.

I don’t know what the answer is. Perhaps externalizing unstable or internal pip functionality into a stable repo. Or maybe establishing a closer working relationship with the pip core dev team to catch these issues in advance. I would hope the core dev team does take these issues seriously though, as their tool’s credibility is on the line.

**Pull request merged**
