### PR TITLE
ci: Travis: test pypy/pypy3 only with PIP=latest

### PR DESCRIPTION
**Pull request by blueyed**
This is mainly meant to reduce the number of jobs (58 currently!).

### CODE REVIEW

**Comment by blueyed** [comment]
Travis jobs are down to 45 (from 58) with this: https://travis-ci.org/jazzband/pip-tools/builds/500616125.

**Comment by blueyed** [comment]
Canceled AppVeyor, to save the environment and because it is not necessary to check.
But hopefully Codecov complains about dropped coverage.

**Comment by atugushev** [comment]
Unfortunately, I don't clearly understand why it should be tested only on the latest PIP. Could you explain that?

**Comment by atugushev** [comment]
@blueyed probably that's because on a pypy test are too slow (x2 time)?

**Comment by blueyed** [comment]
It is meant to reduce the number of jobs.

But it is also true that pypy is slower with coverage (so much that pytest does not run it with coverage in the first place, but here it is still okish).

**Comment by atugushev** [comment]
@blueyed I'd happy to see this merged. Could we get this done?

**Comment by blueyed** [comment]
@atugushev 
I think it is good (AppVeyor was canceled manually).
I don't remember why I've changed the title to WIP - sorry for the confusion.

**Comment by blueyed** [comment]
(closed accidentally.. :/)

**Pull request merged**
