### PR TITLE
Prefer dict over OrderedDict

### PR DESCRIPTION
**Pull request by jdufresne**
Starting with Python 3.6, the builtin dict retains its order. Using
OrderedDict is no longer necessary.

##### Contributor checklist

- [ ] Provided the tests for the changes.
- [x] Gave a clear one-line description in the PR (that the maintainers can add to CHANGELOG.md on release).
- [x] Assign the PR to an existing or new milestone for the target version (following [Semantic Versioning](https://blog.versioneye.com/2014/01/16/semantic-versioning/)).

### CODE REVIEW

**Comment by atugushev** [comment]
Dictionary order is guaranteed since python 3.7:

https://docs.python.org/3/library/stdtypes.html
> Changed in version 3.7: Dictionary order is guaranteed to be insertion order.

or 3.6?

**Comment by webknjaz** [comment]
@atugushev de-jure, the guarantee is for 3.7+ (language-wise) but de-facto CPython 3.6 dicts do preserve the order (which may be different for other runtimes like PyPy, MicroPython etc).

**Comment by jdufresne** [comment]
Exactly right. Here is some more details from the 3.6 release notes:

https://docs.python.org/dev/whatsnew/3.6.html#new-dict-implementation

> The order-preserving aspect of this new implementation is considered an implementation detail and should not be relied upon (this may change in the future, ...

PyPy shares this behavior and is in fact the inspiration for CPython's change. So we can rely on the same behavior there.

**Review by atugushev — APPROVED** [review]
👍🏼

**Comment by webknjaz** [comment]
> PyPy shares this behavior and is in fact the inspiration for CPython's change. So we can rely on the same behavior there.

I think it's okay for as long as we don't support things like MicroPython (this one couldn't implement the same data structure because there was not enough memory on microcontrollers IIRC, dunno if it's been addressed by now).

**Pull request merged**
