### PR TITLE
Promote #pip-tools chat on pypa discord server

### PR DESCRIPTION
**Pull request by atugushev**
@jazzband/pip-tools 

There was [discussion](https://github.com/jazzband/help/issues/22) about chats on jazzband projects, but it's stuck. I've asked to create a chat for pip-tools on PyPA discord server, so [here it is](https://discord.com/channels/803025117553754132/1092653291093102622/1093303545102598207). Why can't we use it as an official chat? Any objection?

### CODE REVIEW

**Comment by ssbarnea** [comment]
pypa discord is far more appropriate for discussions, being closer to pip and the rest of packaging tool. You have all my support!

**Comment by webknjaz** [comment]
FWIW I kinda like Matrix more than discord.

**Comment by atugushev** [comment]
Agreed with @ssbarnea. Let's get this merged then?

**Comment by webknjaz** [comment]
I think that regardless of whether this is merged, we do need matrix presence. I've made a Jazzband space there some time ago and Jannis has put it up next to the org URL already. It allows grouping Jazzband projects and it currently has a generic room and it also exposes the old IRC room that's existed for ages. Matrix has a built-in bridge to Libera.chat so this automatically connects people from both networks.
I've seen someone else having a bridge room that connects their matrix room with other spaces, including discord. So we'd definitely have to try setting up such a connection, if it's possible in a low-maintenance way.

**Comment by webknjaz** [comment]
This is the link, by the way: https://matrix.to/#/%23jazzband:matrix.org

**Comment by chrysle** [comment]
> Agreed with @ssbarnea. Let's get this merged then?

That's still another merge conflict for the README conversion. Can you wait until that is cleared out?

**Comment by chrysle** [comment]
@atugushev Thank you! Can I push to your branch then to resolve the conflict?

**Comment by webknjaz** [comment]
This could still be useful for some. Also, it should be possible to bridge Matrix and discord..

**Comment by atugushev** [comment]
Resolved conflicts on README.

**Comment by webknjaz** [comment]
Could you also add a link to `setup.cfg` or wherever we keep the metadata?

**Comment by webknjaz** [comment]
Looks like I didn't add matrix there either. I guess this can be separate.

**Review by webknjaz — APPROVED** [review]

**Pull request merged**
