### PR TITLE
Run `pre-commit autoupdate`

### PR DESCRIPTION
**Pull request by jdufresne**
Co-authored-by: Albert Tugushev <albert@tugushev.ru>

### CODE REVIEW

**Comment by jdufresne** [comment]
If the project wants to use https://pre-commit.ci/ a bot will handle this automatically.

**Review by atugushev — APPROVED** [review]
I’m on board for pre-commit.ci

**Comment by jdufresne** [comment]
> I’m on board for pre-commit.ci

@jezdez is that something we need you for? Are you able to enable it?

**Comment by jezdez** [comment]
> > I’m on board for pre-commit.ci
> 
> @jezdez is that something we need you for? Are you able to enable it?

I've been using it for the Jazzband website code as well and like it, it's much easier to have all linting happening there than manually deal with configuration. Lemme enable it here and we can collect some experience with an actual Jazzband project. Cheers!

**Comment by jezdez** [comment]
https://results.pre-commit.ci/repo/github/5746963 is the repo info, maybe add a badge as well?

**Comment by jezdez** [comment]
Oh and the QA GitHub Actions workflow could be removed now as well

**Comment by jdufresne** [comment]
Thanks!

**Comment by jdufresne** [comment]
Those tasks are done in #1319.

**Pull request merged**
