### PR TITLE
Fixing issue with losing data about local files

### PR DESCRIPTION
**Pull request by microcat49**
Fixes the loss of information in resolver where we were not keeping track of the InstallRequirements local file information.
 

##### Contributor checklist

- [x] Provided the tests for the changes.
- [x] Gave a clear one-line description in the PR (that the maintainers can add to CHANGELOG.md on release).
- [ ] Assign the PR to an existing or new milestone for the target version (following [Semantic Versioning](https://blog.versioneye.com/2014/01/16/semantic-versioning/)).

### CODE REVIEW

**Comment by microcat49** [comment]
@atugushev sorry about the delayed response. I think the 3.10 python test failure is due to something that is not related to my code. This PR is ready for review.

**Comment by FlorentJeannot** [comment]
To help you understand this fix/enhancement, from the master branch, try the following tests:

### Test 1

In `pip-tools/tests/test_data/packages/fake_with_deps/setup.py`, add in `install_requires`:
```python
"requests @ git+git://github.com/psf/requests@v2.25.1"
```

In `test_realistic_complex_sub_dependencies`, add the following at the end:
```python
print(out.stderr)
assert "requests @ git+git://github.com/psf/requests@v2.25.1" in out.stderr
```

This test will fail because it is missing the direct reference, inside the output there is:
```
git+git://github.com/psf/requests@v2.25.1
```

Also, note that there is no `egg` specified.

### Test 2

In `pip-tools/tests/test_resolver.py`, add the following:

```python
def test_combine_install_requirements_direct_ref(repository, from_line):
    first_dep = from_line("git+ssh://****@bitbucket.org/private-bucket/enums.git@4.0.0", comes_from="-r requirements.in")
    second_dep = from_line("git+ssh://****@bitbucket.org/private-bucket/enums.git@4.0.0", comes_from="-r dev-requirements.in")

    combined = combine_install_requirements(repository, [first_dep, second_dep])
    assert combined.comes_from == first_dep.comes_from  # shortest string
    assert set(combined._source_ireqs) == {first_dep, second_dep}
    assert str(combined.req.specifier) == ""
```

This is failing because both names are missing a specifier. You can make the test pass by specifying a direct reference or an egg:

- `enums @ git+ssh://****@bitbucket.org/private-bucket/enums.git@4.0.0`
- `git+ssh://****@bitbucket.org/private-bucket/enums.git@4.0.0#egg=enums`

For example this works:

```python
def test_combine_install_requirements_direct_ref(repository, from_line):
    first_dep = from_line("enums @ git+ssh://****@bitbucket.org/private-bucket/enums.git@4.0.0", comes_from="-r requirements.in")
    second_dep = from_line("git+ssh://****@bitbucket.org/private-bucket/enums.git@4.0.0#egg=enums", comes_from="-r dev-requirements.in")

    combined = combine_install_requirements(repository, [first_dep, second_dep])
    assert combined.comes_from == first_dep.comes_from  # shortest string
    assert set(combined._source_ireqs) == {first_dep, second_dep}
    assert str(combined.req.specifier) == ""
```

### Conclusion

- Test 1 does not generate the requirement with the direct reference, even though it was specified in `install_requires `
- Test 2 fails if a specifier (a direct reference or an egg) is missing

Because `pip-tools` does not handle direct references, when:

- `requirements.in` contains a direct reference
- `dev-requirements.in` contains the same direct reference

Then the resolver fails when entering `combine_install_requirements`.

I hope this helps to make it clearer and I am looking forward to reading your feedback!

**Comment by azaghal** [comment]
Is there anything that could be done to get this pull request moving forward?

**Comment by adaamz** [comment]
ping @microcat49

**Comment by AndydeCleyre** [comment]
I'm going to close this in favor of focusing related attention on #1519. Thank you for this, and please let me know if something's amiss!

**Pull request closed without merging**
