### PR TITLE
Add info to README about layered requirements files

### LINKED ISSUE #398: Workflow for layered requirements (e.g. prod<-test<-dev requirements)?
Say I have

`requirements.in`:

```
Django~=1.8.0
```

And also

`requirements-dev.in`:

```
django-debug-toolbar
```

How can I run pip-compile on requirements-dev.in, where it will also take into account the requirements in requirements.in when figuring out which versions to use?

For now I have an ad-hoc script that compiles requirements.in first, then requirements-dev.in has `-r requirements.txt` as its first line. Is this an okay workflow? I'm worried that in the future if I add a dependency it will try and update a bunch of stuff I don't want it to update, but I haven't actually used this tool long enough to determine whether that's truly a problem. Wondering if anyone else has used pip-tools in this fashion and has any advice?

### PR DESCRIPTION
**Pull request by jamescooke**
Hopefully fixes #398 :crossed_fingers: 

**Changelog-friendly one-liner:** Add info to README about layered requirements files and `-c` flag

##### Contributor checklist

Not sure how to address these - sorry...

- ~~Provided the tests for the changes.~~
- [x] Requested a review from another contributor.
- [ ] Gave a clear one-line description in the PR (that the maintainers can add to CHANGELOG.md on release).
- [x] Assign the PR to an existing or new milestone for the target version (following [Semantic Versioning](https://blog.versioneye.com/2014/01/16/semantic-versioning/)).

### CODE REVIEW

**Comment by jamescooke** [comment]
This is broken because master is broken :disappointed: 

Latest PR that seems to have introduced the breakage is here: https://github.com/jazzband/pip-tools/pull/864

Bump me when master is green again and I can merge the fixes.

**Comment by atugushev** [comment]
> This is broken because master is broken 😞
> 
> Latest PR that seems to have introduced the breakage is here: #864

Looks like I've forgotten to make pip19.3 as allowed to fail.

**Comment by jamescooke** [comment]
@atugushev Thanks for all the suggestions - I've merged them all in.

Just waiting for the master fix now (https://github.com/jazzband/pip-tools/pull/906) :+1:

**Comment by atugushev** [comment]
@jamescooke 

Thanks for addressing my review comments! Could you also add a "Changelog-friendly one-liner" to the issue text?

**Comment by jamescooke** [comment]
@atugushev NP. Thanks for helping me on this PR :+1: 

I have added the one-liner to the description - hope it's suitable.

**Comment by atugushev** [comment]
Great! I'm going to merge this, despite failing CI, since the [TOXENV=readme](https://travis-ci.org/jazzband/pip-tools/jobs/588651454) CI job is green.

**Comment by atugushev** [comment]
@jamescooke thank you so much for working on this! Appreciate it!

**Pull request merged**
