### PR TITLE
Add pip>=20.3 support

### PR DESCRIPTION
**Pull request by atugushev**
1. Support `pip=>20.3`
2. Introduce new tox env: `tox -e pipprevious`
3. Update CI to run latest and previous versions of `pip`

**Changelog-friendly one-liner**: Add `pip>=20.3` support.

##### Contributor checklist

- [ ] Provided the tests for the changes.
- [x] Gave a clear one-line description in the PR (that the maintainers can add to CHANGELOG.md on release).
- [x] Assign the PR to an existing or new milestone for the target version (following [Semantic Versioning](https://blog.versioneye.com/2014/01/16/semantic-versioning/)).

### CODE REVIEW

**Comment by AndydeCleyre** [comment]
@atugushev Looks like we've got to add compatibility for the new merging of `download_dir` and `wheel_download_dir`. Please see my added and reverted commit, which I *think* would be fine if we were only supporting `>=20.3`.

I'll try to get back to this very soon to make it compatible with older releases as well.

**Comment by AndydeCleyre** [comment]
Ideally we can push a release out before the `pip 20.3` release, which is imminent.

**Comment by groodt** [comment]
The 2.3 beta 1 is now on pypi https://pypi.org/project/pip/20.3b1/

**Comment by AndydeCleyre** [comment]
OK, we've got at least one more recent change in `pip` that require attention here:

- `parse_requirements` drops its `comes_from` argument https://github.com/pypa/pip/pull/8551 -- but I don't think we use that. `comes_from` is used elsewhere for other things, which should be fine.
- `_resolve_one` is not present in the new resolver -- this needs addressing. I'm having a look now.

**Comment by AndydeCleyre** [comment]
Notes on the `_resolve_one` issue: 

- that method remains in the legacy resolver, which may be used by users of `pip>=20.3`, so a version check isn't going to cut it. 
- I don't know how our support for choosing the resolver will really be, but my priority is keeping this usable at all with the new `pip` and new resolver.

**Comment by AndydeCleyre** [comment]
I'm trying to understand the use and purpose of `_resolve_one`, by `pip-tools`. It was introduced in 1db139ce8b456562ea4722fc006db2558dd8f15b, which says:

> Incorporate changes from https://github.com/jazzband/pip-tools/pull/666#issuecomment-397297582

I welcome any extra notes from @techalchemy 

Link to [that comment](https://github.com/jazzband/pip-tools/pull/666#issuecomment-397297582)

I don't understand yet. Obviously it resolves dependencies. It partially may be about filtering direct requirements from the results. It also looks like it's used to "prepare" the reqs.

For now I'm trying using `pip`'s resolver's `resolve` method instead while working it out.

I also now realize that the pip version checks we already have in this PR are not going to cut it when the user has newer pip, but passes `--pip-args --use-deprecated=legacy-resolver`. I don't know a good way to detect which resolver is active -- some `isinstance` check, or attribute check, or something? For now I'm catching `AttributeError`s to guess, but hopefully we can work out something better. 

We may want to modify most or all of the compile cli tests to run again with that option, if the pip version is new enough...

**Comment by groodt** [comment]
Looks like it's going GA very soon: https://github.com/pypa/pip/issues/8936#issuecomment-730018297

**Comment by pradyunsg** [comment]
Ask me anything you want, regarding the new resolver in pip and the internal model/design of the various components (from pip's PoV)! :)

**Comment by atugushev** [comment]
@AndydeCleyre thank you very much for helping me with `pip-20.3` 🙏 

> I don't know a good way to detect which resolver is active -- some `isinstance` check, or attribute check, or something? For now I'm catching `AttributeError`s to guess, but hopefully we can work out something better.

It seems for now we should pass `--use-deprecated=legacy-resolver` option to the `InstallComamnd` to force pip to use legacy resolver until pip-tools would support new resolver. See a1e34a7.

---

@pradyunsg thank you! Your assistance would help a lot when we start to work on the new resolver!

**Comment by AndydeCleyre** [comment]
I'm sorry I haven't been more helpful on this.

**Comment by atugushev** [comment]
It's ready for review, and yeah it's better to merge and release this before pip-20.3 being released (which is today 😰)

**Review by vphilippon — APPROVED** [review]
LGTM 👍

**Comment by atugushev** [comment]
@vphilippon thanks for reviewing this! I'll merge this then eagerly if nobody minds.

**Comment by atugushev** [comment]
Ah, no I can't. Travis is still `pending` since yesterday :(

**Comment by vphilippon** [comment]
@atugushev Yeah I saw that. I cancelled and retried the build in hope to get it unstuck, but to no avail.
I was going to ask if that was something you knew about.

**Comment by atugushev** [comment]
@vphilippon not that I'm aware of. Maybe we have reached free credit for free usage? See also https://github.com/jazzband-roadies/help/issues/206#issuecomment-731197268

**Comment by pradyunsg** [comment]
I'd suggest turning Travis CI off, because they have an open source plan "in progress" and not actually rolled out to any project AFAIK. The one-time credit limit they announced is like 16 hours of CI time, which just isn't enough.

**Comment by pradyunsg** [comment]
https://github.com/jazzband/pip-tools/pull/1229 is the relevant PR. :)

**Comment by hugovk** [comment]
> I'd suggest turning Travis CI off, because they have an open source plan "in progress" and not actually rolled out to any project AFAIK. The one-time credit limit they announced is like 16 hours of CI time, which just isn't enough.

Raku is the only project I've seen which has been granted something:

* https://twitter.com/jjmerelo/status/1324272244349173760

I've applied but not got anything yet. But, yeah, https://github.com/jazzband/pip-tools/pull/1229 :)

**Comment by groodt** [comment]
Thanks for the quick turnaround all!

**Pull request merged**
