### PR TITLE
Full test coverage for compile and sync module

### PR DESCRIPTION
**Pull request by atugushev**
Adds tests for sync/compile modules to increase the test coverage up to 100% of the following files:

- piptools/scripts/compile.py
- piptools/scripts/sync.py
- piptools/sync.py

### CODE REVIEW

**Comment by blueyed** [comment]
Needs to be rebased.
Then hopefully the code offsets/diff with https://codecov.io/gh/jazzband/pip-tools/pull/747/changes are correct also.

It looks like there was still some branch missing at least - but still an improvement, of course!

**Comment by atugushev** [comment]
@blueyed i've rebased it. 

It seems we have a regression bug from #731. See the [failed build](https://travis-ci.org/jazzband/pip-tools/jobs/499761026). At least we have a benefit from this PR :)

I'll make a new PR with the fix and proper test ported from this PR.

**Comment by blueyed** [comment]
:+1: 
I've created https://github.com/jazzband/pip-tools/pull/748 to handle CI better in this case.

**Comment by atugushev** [comment]
I've rebased it again. It's ready to review.

**Comment by atugushev** [comment]
@blueyed thanks!

**Pull request merged**
