### PR TITLE
Test on Python 3.12

### PR DESCRIPTION
**Pull request by atugushev**
##### Contributor checklist

- [x] Provided the tests for the changes.
- [x] Assure PR title is short, clear, and good to be included in the user-oriented changelog

##### Maintainer checklist

- [x] Assure one of these labels is present: `backwards incompatible`, `feature`, `enhancement`, `deprecation`, `bug`, `dependency`, `docs` or `skip-changelog` as they determine changelog listing.
- [x] Assign the PR to an existing or new milestone for the target version (following [Semantic Versioning](https://blog.versioneye.com/2014/01/16/semantic-versioning/)).

### CODE REVIEW

**Review by ssbarnea — APPROVED** [review]

**Comment by webknjaz** [comment]
@atugushev instead of deadsnakes you could just use `~3.12.0-0` from GH

**Comment by atugushev** [comment]
@webknjaz I followed the pattern in `ci.yaml`. Isn't "deadsnakes"  build's main python nightly which is why we use it?

**Comment by webknjaz** [comment]
Yes and no. Deadsnakes builds CPython's repo branch every day. It is truly unstable.
GitHub builds tagged releases, they are updated less frequently, providing less surprises every day.
Originally, deadsnakes were used because GH was slow to provide alphas and to emulate what Travis CI used to have.
So depending on the motivation, you might want to use one or the other.

**Comment by atugushev** [comment]
@webknjaz thanks for the info. I guess we can switch to GHA completely then. I'll open a PR shortly.

**Pull request merged**
