### PR TITLE
Replace custom logging with built-in version.

### LINKED ISSUE #362: pip-tools logger should always go to stderr
I noticed that pip-tools's logger (called [`LogContext` here](https://github.com/nvie/pip-tools/blob/d521d766113e69ea0a10017bb968d3b3bb242e5f/piptools/logging.py#L10)) sometimes writes to stdout (depending on the log level).

It would be best if the logger always writes to stderr since a logger is for monitoring / diagnostic purposes, and its messages can interfere if one is trying to capture the "output" portion of running the script. This would help in addressing some of the other pip-tools issues related to stdout and stderr.

In cases where stdout is needed, a separate function can be used (e.g. `print()`). This would help in separating pip-tools's "API" (stdout) from its diagnostic / progress reporting (stderr).

### PR DESCRIPTION
**Pull request by cmc333333**
Rather than write to stdout via click.echo, use Python's built-in logging
mechanism. This is a bit more conventional and could allow users to configure
logs more thoroughly. It should also resolve #362.

To match the ANSI colors, this now imports the coloredlogs module.

##### Contributor checklist

- [ ] ~Provided the tests for the changes~ (N/A, refactor)
- [x] Added the changes to CHANGELOG.md
- [ ] Requested (or received) a review from another contributor

### CODE REVIEW

**Comment by jdufresne** [comment]
I like the idea of moving away from click and towards using the stdlib for logging. In doing so, can we avoid introducing a new dependency, coloredlogs? It seems as pip-tools is a very low level tool used to build projects instead of consumed directly by projects it should strive for a minimal number of dependencies.

**Comment by cmc333333** [comment]
While I'm generally in favor of reducing dependencies, the `coloredlogs` library is tailor-fit to this situation. Python's logging system isn't aware of ANSI colors (they don't make sense when outputting to a file, constructing JSON for logstash, etc.). `coloredlogs` allows us to add that back when writing to the console (while avoiding it for other outputs) to match the existing functionality.

I think that leaves us with a few possibilities:

1. Continue to write everything to stdout and skip Python's logging system. This is not a great solution as it mixes different types of messages and doesn't allow the logs to be configured.
2. Use Python's logging system, but don't attempt to colorize the stdout/stderr logs. This is a regression in terms of functionality.
3. Use Python's logging system and `coloredlogs`. This solves the problems of 1 and 2, but adds a new dependency.
4. Use Python's logging system and re-implement `coloredlogs` in pip-tools. This is also a less-than-optimal solution as it requires new tests and maintenance for the pip-tools team. It's also trading a custom logging system for a custom coloring system, which isn't as significant a step forward.

**Comment by jdufresne** [comment]
Thanks for the analysis and reasoning. I agree that 1 & 4 are definitely not wanted. Your considerations of the trade offs are very fair.

**Comment by vphilippon** [comment]
I'm like the idea. The only thing bugging me is the effect of a pip-sync for an app also using `coloredlogs`.
I did a simple test with your branch on Windows:
requirements.in:
```
coloredlogs<6.0
```
then
```
$ pip-compile
$ pip-sync
```
and it went well, no problem with modifying `coloredlogs` while `pip-sync` used it itself.
(If only it could go that well all the time... *sigh*).
That was a really simple test, it would probably be a good idea to do test the behaviour a bit more.

Note, I actually managed to "break" `pip-sync` doing this:
requirements.in:
```
coloredlogs<1.0
```
then
```
$ pip-compile
$ pip-sync
```
ending up with `coloredlogs==0.8` installed, which broke pip-sync.
So to be nice, we should set a lower bound on coloredlogs, so that running `pip check` will tell that something is wrong in that case.

I'll make a more complete review after the branch is rebased with the latest changes.

**Comment by jdufresne** [comment]
Maybe it would be acceptable to just not have colored logging? What are your thoughts?

**Comment by vphilippon** [comment]
Thinking about this over again, this is the same situation with any of of `pip-tools` dependencies (`click` or anything else). I did have to go out of my way a bit to break it. I think a reasonable idea here is to use `coloredlogs`, and put a version specifier, like we should, in `install_requires`. Let's try to put that lower bound as low as possible to minimize the conflict zone. I don't feel like this is lib with a high risk of conflict though.

Sorry for taking so long on this. Its a bit hard to get motivation when you know you're somewhat blocked ahead by being unable to make releases and give value to the time spent. /rant.

**Comment by ssbarnea** [comment]
Too old to be salvageable.

**Pull request closed without merging**
