### PR TITLE
Ignore local hashes with --no-reuse-hashes

### LINKED ISSUE #1176: ignore current hashes using `--no-reuse-hashes`
it might be worth always getting the hashes now rather than skipping them if the hashes are already in the requirements.txt (this behaviour causes me problems, eg when new wheels are uploaded to an old version I don't get the hash of the new wheel)

We could ignore current hashes using `--rebuild`. What do you think?

_Originally posted by @atugushev in https://github.com/jazzband/pip-tools/pull/1109#issuecomment-616114776_

see also https://github.com/jazzband/pip-tools/pull/641/files

### PR DESCRIPTION
**Pull request by graingert**
Fixes #1176

**Changelog-friendly one-liner**: Ignore local hashes with `--no-reuse-hashes` in `pip-compile`

##### Contributor checklist

- [x] Provided the tests for the changes.
- [x] Gave a clear one-line description in the PR (that the maintainers can add to CHANGELOG.md on release).
- [x] Assign the PR to an existing or new milestone for the target version (following [Semantic Versioning](https://blog.versioneye.com/2014/01/16/semantic-versioning/)).

### CODE REVIEW

**Comment by graingert** [comment]
https://github.com/jazzband/pip-tools/pull/1176

**Comment by graingert** [comment]
@atugushev do I need to get a review from another maintainer?

**Comment by atugushev** [comment]
@graingert one approval is enough 👍 I'm going to prepare a release soon, right before `pip-20.2` will be released.

**Comment by atugushev** [comment]
`pip-tools v5.3.0` is released.

**Comment by graingert** [comment]
@atugushev amazing, thanks again!

**Pull request merged**
